import Footer from "../components/Layout/Footer"
import Header from "../components/Layout/Header"
import { sora } from "./fonts"
import "../styles/burger.css"
import "../styles/index.css"



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
